const mongoose = require('mongoose');

const inventorySchema = mongoose.Schema({
    bloodBankID:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'BloodBank'
    },
    rbc:{
        "A+Ve":{type:Number},
        "A-Ve":{type:Number},
        "AB+Ve":{type:Number},
        "AB-Ve":{type:Number},
        "B+Ve":{type:Number},
        "B-Ve":{type:Number},
        "O+Ve":{type:Number},
        "O-Ve":{type:Number}
    },
    wbc:{
        "A+Ve":{type:Number},
        "A-Ve":{type:Number},
        "AB+Ve":{type:Number},
        "AB-Ve":{type:Number},
        "B+Ve":{type:Number},
        "B-Ve":{type:Number},
        "O+Ve":{type:Number},
        "O-Ve":{type:Number}
    },
    cryo :{
        "A+Ve":{type:Number},
        "A-Ve":{type:Number},
        "AB+Ve":{type:Number},
        "AB-Ve":{type:Number},
        "B+Ve":{type:Number},
        "B-Ve":{type:Number},
        "O+Ve":{type:Number},
        "O-Ve":{type:Number}
    },
    plasma:{
        "A+Ve":{type:Number},
        "A-Ve":{type:Number},
        "AB+Ve":{type:Number},
        "AB-Ve":{type:Number},
        "B+Ve":{type:Number},
        "B-Ve":{type:Number},
        "O+Ve":{type:Number},
        "O-Ve":{type:Number}
    },
    platelate:{
        "A+Ve":{type:Number},
        "A-Ve":{type:Number},
        "AB+Ve":{type:Number},
        "AB-Ve":{type:Number},
        "B+Ve":{type:Number},
        "B-Ve":{type:Number},
        "O+Ve":{type:Number},
        "O-Ve":{type:Number}
    },
    ffp:{
        "A+Ve":{type:Number},
        "A-Ve":{type:Number},
        "AB+Ve":{type:Number},
        "AB-Ve":{type:Number},
        "B+Ve":{type:Number},
        "B-Ve":{type:Number},
        "O+Ve":{type:Number},
        "O-Ve":{type:Number}
    },
    whole:{
        "A+Ve":{type:Number},
        "A-Ve":{type:Number},
        "AB+Ve":{type:Number},
        "AB-Ve":{type:Number},
        "B+Ve":{type:Number},
        "B-Ve":{type:Number},
        "O+Ve":{type:Number},
        "O-Ve":{type:Number}
    },
    sagm:{
        "A+Ve":{type:Number},
        "A-Ve":{type:Number},
        "AB+Ve":{type:Number},
        "AB-Ve":{type:Number},
        "B+Ve":{type:Number},
        "B-Ve":{type:Number},
        "O+Ve":{type:Number},
        "O-Ve":{type:Number}
    },
    sdplate:{
        "A+Ve":{type:Number},
        "A-Ve":{type:Number},
        "AB+Ve":{type:Number},
        "AB-Ve":{type:Number},
        "B+Ve":{type:Number},
        "B-Ve":{type:Number},
        "O+Ve":{type:Number},
        "O-Ve":{type:Number}
    },
    sdplasma:{
        "A+Ve":{type:Number},
        "A-Ve":{type:Number},
        "AB+Ve":{type:Number},
        "AB-Ve":{type:Number},
        "B+Ve":{type:Number},
        "B-Ve":{type:Number},
        "O+Ve":{type:Number},
        "O-Ve":{type:Number}
    }
    
});

module.exports = mongoose.model('Inventory',inventorySchema);